bookshelf_net.o: bookshelf_net.h
	g++ -c bookshelf_net.cpp bookshelf_net_parser.hpp

bookshelf_node.o: bookshelf_node.h
	g++ -c bookshelf_node.cpp bookshelf_node_parser.hpp

bookshelf_pl.o: bookshelf_pl.h
	g++ -c bookshelf_pl.cpp bookshelf_pl_parser.hpp

clean:
	rm *.o
